### ISSUE TITLE
fastrank is not automatically installed upon installation

### ISSUE THREAD

**Issue by adknudson** [SchisslerGroup/bigsimr#1]
[fastrank](https://github.com/douglasgscofield/fastrank) is a dependency that must be installed from github. Either we should find a different package for fast rank computations or make it so that `bigsimr` checks for the package and installs it upon load/installation.

**Comment by grizant** [comment]
I'm not sure how essential fastrank is but I believe it is to compute
spearman's rho.

Are you saying that any package we use must be on Cran? Or bioconductor? Is
that soyou auto install of dependencies? Or what?

Typically when I install a package, like tcga2stat that requires a
bioconductor package, and it fails. I Google the offending package and
install manually. Then retry the original install. This happens all the
time.

But I agree we should be selective and make the install be easy. A CRAN
package is really nice. So lets see if fastrank is needed and if so search
for an alternative on Cran. If unavailable then we just print install lines
as part of the package failed messages.

Please create a Trello card and lead the task. If you need something just
ask.

Thanks,

Alfred "Grant" Schissler
Assistant Professor, Statistics
Mathematics & Statistics
1664 North Virginia St
MS 0084, DMS 224
Pronouns: Dr.

work-phone: 775-784-4661
email: aschissler@unr.edu
website: https://www.grantschissler.com

**Comment by adknudson** [comment]
[fastrank](https://github.com/douglasgscofield/fastrank) has been added as a remote import. It will now be automatically installed with bigsimr.

**Comment by adknudson** [comment]
[fastrank](https://github.com/douglasgscofield/fastrank) has been added as a remote import. It will now be automatically installed with bigsimr.
