### ISSUE TITLE
Look into speeding up Matrix::nearPD()

### ISSUE THREAD

**Issue by adknudson** [SchisslerGroup/bigsimr#7]

**Comment by grizant** [comment]
https://cran.r-project.org/web/packages/CovTools/CovTools.pdf

**Comment by adknudson** [comment]
With the addition of `nearPSDcor()`, I can close this issue. nearPSDcor() is a quadratically convergent method for finding the nearest positive semi-definite correlation matrix and should be faster than `Matrix::nearPD()` for larger matrices. I will begin integration and Rcpp speedups in the coming days.
